services:
  valkey:
    image: valkey/valkey:7.2-alpine
    container_name: valkey-use-cases
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data
    command: valkey-server --appendonly yes
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  valkey_data:
    driver: local
